import { useState } from 'react';
import { ChemicalFormula, IonNotation, MathBlock, MathInline, NuclearNotation, ScientificValue } from './components/science';

const nuclei = [['H',1],['C',6],['N',7],['O',8],['Cl',17],['Mg',12],['Al',13],['Ca',20],['Fe',26],['Na',11]] as const;
function Header() { return <header className="topbar"><div className="brand"><span className="brand-mark">∿</span><span><b>مِرْصاد</b><small>مختبر العلوم التفاعلي</small></span></div><nav><a className="active" href="#lab">المختبر العلمي</a><a href="#units">الوحدات</a><a href="#about">عن المنصة</a></nav><button className="avatar" aria-label="الملف الشخصي">س</button></header>; }
function Sidebar() { return <aside className="sidebar"><div className="eyebrow">مسار الاستكشاف</div><div className="side-title">أساسيات العلوم <span>01</span></div><div className="side-progress"><i /></div><ul><li className="selected"><span>◈</span> مختبر التمثيل العلمي <b>الآن</b></li><li><span>◌</span> مدخل إلى الفيزياء <em>قريباً</em></li><li><span>◇</span> المادة وتحوّلاتها <em>قريباً</em></li></ul><div className="side-note"><span>✦</span><div><b>تعلّم بفضول</b><small>كل تجربة تفتح سؤالاً جديداً.</small></div></div></aside>; }
function Lab() { const [tab, setTab] = useState('all'); return <main className="content" id="lab"><div className="crumbs">الرئيسية <span>·</span> أساسيات العلوم <span>·</span> <b>مختبر التمثيل العلمي</b></div><section className="intro"><div><div className="eyebrow">استوديو  /  ٠١</div><h1>مختبر التمثيل <span>العلمي</span></h1><p>مساحة تفاعلية نختبر فيها كيف تتحدث الرموز والمعادلات بلغة واضحة، مهما تغيّر اتجاه الصفحة.</p></div><div className="intro-orbit"><span>Δ</span><i>π</i><b>⚛</b></div></section><div className="tabs" role="tablist">{[['all','نظرة عامة'],['nuclear','الذرات'],['math','المعادلات']].map(([id,label])=><button key={id} className={tab===id?'current':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{(tab==='all'||tab==='nuclear') && <NuclearSection />}{(tab==='all'||tab==='math') && <MathSection />}{tab==='all' && <ArabicSection />}</main>; }
function NuclearSection() { return <section className="lab-section"><div className="section-heading"><div><span className="section-number">01</span><h2>الترميز النووي</h2><p>كل رقم له مكانه، وكل مكان يحكي جزءاً من قصة الذرة.</p></div><span className="direction-badge">LTR  /  isolated</span></div><div className="science-card"><div className="card-label">العدد الذري فقط</div><div className="nuc-row">{nuclei.map(([symbol,n])=><div className="nuc-item" key={symbol}><NuclearNotation symbol={symbol} atomicNumber={n}/><small>{symbol}</small></div>)}</div></div><div className="two-cards"><div className="science-card"><div className="card-label">الكتلة + العدد الذري</div><div className="nuc-row compact"><NuclearNotation symbol="H" atomicNumber={1} massNumber={1}/><NuclearNotation symbol="C" atomicNumber={6} massNumber={12}/><NuclearNotation symbol="C" atomicNumber={6} massNumber={14}/><NuclearNotation symbol="Cl" atomicNumber={17} massNumber={35}/><NuclearNotation symbol="Na" atomicNumber={11} massNumber={23}/></div></div><div className="science-card charge-card"><div className="card-label">مع الشحنة</div><div className="nuc-row compact"><NuclearNotation symbol="Cl" atomicNumber={17} massNumber={35} charge="−"/><NuclearNotation symbol="Na" atomicNumber={11} charge="+"/><NuclearNotation symbol="Ca" atomicNumber={20} charge="2+"/></div></div></div><div className="formula-strip"><span>صيغ كيميائية</span><ChemicalFormula formula="H2O"/><ChemicalFormula formula="CO2"/><ChemicalFormula formula="CaCO3"/><ChemicalFormula formula="H2SO4"/><span className="rule" /><IonNotation species="SO4" charge="2−" /></div></section>; }
function MathSection() { return <section className="lab-section math-section"><div className="section-heading"><div><span className="section-number">02</span><h2>لغة المعادلات</h2><p>المعادلة أداة تفكير، وليست مجرد رموز على الصفحة.</p></div><span className="direction-badge">KaTeX  /  precise</span></div><div className="equation-grid"><div className="equation-card"><span>علاقات أساسية</span><MathInline tex="v = \\frac{d}{t}"/><MathInline tex="F = ma"/><MathInline tex="\\rho = \\frac{m}{V}"/><MathInline tex="Q = mc\\Delta T"/></div><div className="equation-card large"><span>صيغة كتلية</span><MathBlock tex="E = mc^2" label="معادلة الطاقة والكتلة"/></div></div><p className="arabic-line">تُحسب السرعة بالعلاقة <MathInline tex="v = d / t" />، وتُقاس بوحدة <ScientificValue value="m/s" />.</p></section>; }
function ArabicSection() { return <section className="lab-section arabic-section"><div className="section-heading"><div><span className="section-number">03</span><h2>العربي والعلمي معاً</h2><p>النص العربي يحافظ على اتجاهه، والعلم يحتفظ ببنيته.</p></div></div><div className="prose-card"><p>تتكون ذرة <NuclearNotation symbol="Cl" atomicNumber={17} massNumber={35} /> من نواة تحتوي على بروتونات ونيوترونات. عند اتحادها مع الصوديوم تتكوّن <ChemicalFormula formula="NaCl" />، وهي صيغة ملح الطعام.</p><p>في التجربة، إذا كانت الكتلة <ScientificValue value="10" unit="kg" /> ودرجة الحرارة <ScientificValue value="25" unit="°C" />، نستخدم العلاقة <MathInline tex="Q = mc\\Delta T" /> لفهم الطاقة الحرارية.</p></div></section>; }
export function App() { return <><Header/><div className="app-layout"><Sidebar/><Lab/></div></>; }
